# Generated by Django 5.2.13 on 2026-04-21 16:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('civil_status', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('highest_education', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('eligibility', models.CharField(choices=[('CSE_PROFESSIONAL', 'CSE Professional'), ('CSE_SUBPROFESSIONAL', 'CSE Subprofessional'), ('BAR', 'Bar'), ('BOARD', 'Board'), ('NONE', 'None')], default='NONE', max_length=25)),
                ('eligibility_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('eligibility_date', models.DateField(blank=True, null=True)),
                ('is_pwd', models.BooleanField(default=False)),
                ('is_solo_parent', models.BooleanField(default=False)),
                ('is_ips', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='recruitment_last_na_96df56_idx'), models.Index(fields=['email'], name='recruitment_email_d9c029_idx'), models.Index(fields=['eligibility'], name='recruitment_eligibi_bda0e3_idx'), models.Index(fields=['created_at'], name='recruitment_created_a19f76_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CASUAL', 'Casual'), ('CONTRACTUAL', 'Contractual')], max_length=20)),
                ('salary_grade', models.PositiveSmallIntegerField()),
                ('plantilla_item_no', models.CharField(blank=True, max_length=100)),
                ('no_of_vacancies', models.PositiveIntegerField(default=1)),
                ('qualification_standards', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=15)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='hr_records.department')),
                ('position_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='hr_records.position')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_interview_schedules', to=settings.AUTH_USER_MODEL)),
                ('panel_members', models.ManyToManyField(blank=True, related_name='interview_panels', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_schedules', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_status', models.CharField(choices=[('RECEIVED', 'Received'), ('SHORTLISTED', 'Shortlisted'), ('EXAM_SCHEDULED', 'Exam Scheduled'), ('EXAM_DONE', 'Exam Done'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('INTERVIEW_DONE', 'Interview Done'), ('FOR_DELIBERATION', 'For Deliberation'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('HIRED', 'Hired'), ('WITHDRAWN', 'Withdrawn')], default='RECEIVED', max_length=25)),
                ('remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.applicant')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_recruitment_applications', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='RankingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_final', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_ranking_lists', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_lists', to='recruitment.jobposting')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interview_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('performance_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank_number', models.PositiveIntegerField()),
                ('is_recommended', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranking_entries', to='recruitment.application')),
                ('ranking_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='recruitment.rankinglist')),
            ],
            options={
                'ordering': ['rank_number'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume'), ('PDS', 'Personal Data Sheet'), ('TOR', 'Transcript of Records'), ('CERT_ELIGIBILITY', 'Certificate of Eligibility'), ('CERT_EMPLOYMENT', 'Certificate of Employment'), ('NBI', 'NBI Clearance'), ('BIRTH_CERT', 'Birth Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='recruitment/documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='recruitment.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_application_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['document_type'], name='recruitment_documen_c87e98_idx'), models.Index(fields=['is_verified'], name='recruitment_is_veri_59c95e_idx'), models.Index(fields=['uploaded_at'], name='recruitment_uploade_ab18aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('REINSTATEMENT', 'Reinstatement')], max_length=20)),
                ('effectivity_date', models.DateField()),
                ('appointment_no', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='recruitment.application')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['appointment_type'], name='recruitment_appoint_d0f275_idx'), models.Index(fields=['effectivity_date'], name='recruitment_effecti_ad5060_idx'), models.Index(fields=['appointment_no'], name='recruitment_appoint_dd4c4c_idx'), models.Index(fields=['issued_at'], name='recruitment_issued__71b00e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('written_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('oral_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='recruitment.application')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rated_exam_results', to=settings.AUTH_USER_MODEL)),
                ('exam_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recruitment.examschedule')),
            ],
            options={
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['application'], name='recruitment_applica_38cbe0_idx'), models.Index(fields=['exam_schedule'], name='recruitment_exam_sc_57d272_idx'), models.Index(fields=['rated_at'], name='recruitment_rated_a_a60e1b_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'exam_schedule'), name='uniq_exam_result_per_schedule')],
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('behavioral_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_results', to='recruitment.application')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rated_interview_results', to=settings.AUTH_USER_MODEL)),
                ('interview_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='recruitment.interviewschedule')),
            ],
            options={
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['application'], name='recruitment_applica_f1e84a_idx'), models.Index(fields=['interview_schedule'], name='recruitment_intervi_9b5443_idx'), models.Index(fields=['rated_at'], name='recruitment_rated_a_f78b14_idx')],
                'constraints': [models.UniqueConstraint(fields=('application', 'interview_schedule'), name='uniq_interview_result_per_schedule')],
            },
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status'], name='recruitment_status_a86dab_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['department'], name='recruitment_departm_94a2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['employment_type'], name='recruitment_employm_87e973_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['salary_grade'], name='recruitment_salary__bd0ccd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['date_posted'], name='recruitment_date_po_b64367_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['deadline'], name='recruitment_deadlin_046a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['job_posting'], name='recruitment_job_pos_6cc8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewschedule',
            index=models.Index(fields=['interview_date'], name='recruitment_intervi_9bdc66_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['job_posting'], name='recruitment_job_pos_ddccd1_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['exam_date'], name='recruitment_exam_da_4ed7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['application_status'], name='recruitment_applica_4f3ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_posting'], name='recruitment_job_pos_5bc0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['date_applied'], name='recruitment_date_ap_d4ced2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant'], name='recruitment_applica_6ae425_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'job_posting'), name='uniq_application_per_posting'),
        ),
        migrations.AddIndex(
            model_name='rankinglist',
            index=models.Index(fields=['job_posting'], name='recruitment_job_pos_76e467_idx'),
        ),
        migrations.AddIndex(
            model_name='rankinglist',
            index=models.Index(fields=['is_final'], name='recruitment_is_fina_31aaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='rankinglist',
            index=models.Index(fields=['generated_at'], name='recruitment_generat_481465_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['ranking_list'], name='recruitment_ranking_685d09_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['rank_number'], name='recruitment_rank_nu_fe99f6_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['total_score'], name='recruitment_total_s_f8c250_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingentry',
            index=models.Index(fields=['is_recommended'], name='recruitment_is_reco_3fd9d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('ranking_list', 'application'), name='uniq_application_per_ranking_list'),
        ),
        migrations.AddConstraint(
            model_name='rankingentry',
            constraint=models.UniqueConstraint(fields=('ranking_list', 'rank_number'), name='uniq_rank_number_per_ranking_list'),
        ),
    ]
