# Generated by Django 5.2.13 on 2026-04-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='hr_records__code_e0806d_idx'), models.Index(fields=['name'], name='hr_records__name_c09a08_idx'), models.Index(fields=['is_active'], name='hr_records__is_acti_0aa0d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('salary_grade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='hr_records.department')),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['code'], name='hr_records__code_428a32_idx'), models.Index(fields=['title'], name='hr_records__title_d50579_idx'), models.Index(fields=['department'], name='hr_records__departm_984f5c_idx'), models.Index(fields=['is_active'], name='hr_records__is_acti_c0e25c_idx')],
            },
        ),
    ]
